# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f99d159177769e3261a83fb4606344fc"
name = "FileMaster - Files Exporter"
handle = "filemaster-exporter"
application_url = "https://file-master.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "filemaster-exporter.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files"

[auth]
redirect_urls = [
  "https://file-master.fly.dev/auth/callback",
  "https://file-master.fly.dev/auth/shopify/callback",
  "https://file-master.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
