# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f99d159177769e3261a83fb4606344fc"
name = "FileMaster - Exporter"
handle = "filemaster-exporter"
application_url = "https://locked-nicholas-timothy-ave.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "filemaster-exporter.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files"

[auth]
redirect_urls = [
  "https://locked-nicholas-timothy-ave.trycloudflare.com/auth/callback",
  "https://locked-nicholas-timothy-ave.trycloudflare.com/auth/shopify/callback",
  "https://locked-nicholas-timothy-ave.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
